.\" Copyright (c) 1980 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)config.8	6.4 (Berkeley) 06/24/90
.\"
.TH CONFIG 8 ""
.UC 4
.SH NAME
config \- build system configuration files
.SH SYNOPSIS
.B config
[
.B \-p
]
.I SYSTEM_NAME
.SH DESCRIPTION
.PP
.I Config
builds a set of system configuration files from a short file which describes
the sort of system that is being configured.  It also takes as input a file
which tells
.I config
what files are needed to generate a system.
This can be augmented by a configuration specific set of files
that give alternate files for a specific machine.
(see the FILES section below)
If the
.B \-p
option is supplied, 
.I config
will configure a system for profiling; c.f.
.IR kgmon (8)
and
.IR gprof (1).
.PP
.I Config
should be run from the
.B conf
subdirectory of the system source (usually /sys/conf).
Its argument is the name of a system configuration file
containing device specifications, configuration options
and other system parameters for one system configuration.
.I Config
assumes that there is already a directory
.I "../SYSTEM_NAME"
created and it places all its output files in there.  
The output of
.I config
consists of a number of files; for the VAX, they are:
.B ioconf.c
contains a description
of what I/O devices are attached to the system,;
.B ubglue.s
contains a set of interrupt service routines for devices
attached to the UNIBUS;
.B ubvec.s
contains offsets into a structure used for counting per-device interrupts;
.B Makefile
is a file used by
.IR make (1)
in building the system; a set of header files contain definitions of
the number of various devices that will be compiled into the system;
and a set of swap configuration files contain definitions for
the disk areas to be used for swapping, the root file system,
argument processing, and system dumps.
.PP
After running
.IR config ,
it is necessary to run ``make depend'' in the directory where the new makefile
was created.
.I Config
prints a reminder of this when it completes.
.PP
If any other error messages are produced by
.I config,
the problems in the configuration file should be corrected and
.I config
should be run again.
Attempts to compile a system that had configuration errors
are likely to meet with failure.
.SH FILES
.nf
/sys/conf/Makefile.vax	generic makefile for the VAX
/sys/conf/files	list of common files system is built from
/sys/conf/files.vax	list of VAX specific files
/sys/conf/devices.vax	name to major device mapping file for the VAX
/sys/conf/files.ERNIE	list of files specific to ERNIE system
.fi
.SH SEE ALSO
``Building 4.3BSD UNIX System with Config''
.br
The SYNOPSIS portion of each device in section 4.
.SH BUGS
The line numbers reported in error messages are usually off by one.
