.\" Copyright (c) 1990, 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)reboot.8	5.1 (Berkeley) 10/28/91
.\"
.Dd 
.Dt REBOOT 8
.Os
.Sh NAME
.Nm reboot
.Nd
restarting the system
.Sh SYNOPSIS
.Nm reboot
.Op Fl nq
.Sh DESCRIPTION
The
.Nm reboot
utility flushes the file system cache to disk, sends all running processes
a SIGTERM (and subsequently a SIGKILL) and restarts the system.
The restart is logged, including entering a shutdown record into the login
accounting file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl n
If the
.Fl n
option is specified,
.Nm reboot
neither flushes the file system cache or does any logging of the restart.
.It Fl q
If the
.Fl q
option is specified,
.Nm reboot
restarts the system quickly and ungracefully.
Processes are not signalled, the file system cache is not flushed and the
restart is not logged.
This option should not be used.
.El
.Pp
Normally, when the system needs to be restarted, the
.Xr shutdown 8
utility is used and users given advance warning of the impending
restart.
.Sh SEE ALSO
.Xr sync 1 ,
.Xr utmp 5 ,
.Xr boot 8 ,
.Xr halt 8 ,
.Xr shutdown 8 ,
.Sh HISTORY
The
.Nm
command is
.Ud .
