#	@(#)Makefile	5.18 (Berkeley) 08/29/92

Missing: adventure boggle ching dungeon hunt phantasia quiz warp 

	chess ching cribbage dm factor fish fortune hack hangman mille \
	monop morse number phantasia pig pom ppt primes quiz rain robots \
	rogue sail snake trek wargames worm worms wump

.include <bsd.subdir.mk>
