.\" Copyright (c) 1986 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)de.4	6.4 (Berkeley) 06/23/90
.\"
.TH DE 4 ""
.UC 5
.SH NAME
de \- DEC DEUNA 10 Mb/s Ethernet interface
.SH SYNOPSIS
.B "device de0 at uba0 csr 174510 vector deintr"
.SH DESCRIPTION
The
.I de
interface provides access to a 10 Mb/s Ethernet network through
a Digital Equipment UNIBUS Network Adapter (DEUNA).
.PP
Each of the host's network addresses
is specified at boot time with an SIOCSIFADDR
ioctl.  The
.I de
interface employs the address resolution protocol described in
.IR arp (4)
to dynamically map between Internet and Ethernet addresses on the local
network.
.PP
The interface normally tries to use a ``trailer'' encapsulation
to minimize copying data on input and output.
The use of trailers is negotiated with ARP.
This negotiation may be disabled, on a per-interface basis,
by setting the IFF_NOTRAILERS
flag with an SIOCSIFFLAGS ioctl.
.SH DIAGNOSTICS
\fBde%d: hardware address %s\fP.
This is a normal autoconfiguration message noting the 6 byte physical
ethernet address of the adapter.
.PP
\fBde%d: oerror, flags=%b tdrerr=%b (len=%d)\fP.
The hardware indicated an error
in transmitting a packet to the cable.
The status and error flags are reported.
.PP
\fBde%d: ierror, flags=%b lenerr=%b (len=%d)\fP.
The hardware indicated an error
in reading a packet from the cable.
The status and error flags are reported.
.PP
\fBde%d: can't handle af%d\fP.  The interface was handed
a message with addresses formatted in an unsuitable address
family; the packet was dropped.
.PP
\fBde%d: buffer unavailable\fP.  The interface received more packets
than it had buffers allocated to receive them.
.PP
\fBde%d: address change failed, csr0=%b csr1=%b\fP.
The interface was unable to reprogram
its physical ethernet address.
This may happen with very early models of the interface.
This facility is used only when
the controller is not the first network interface configured for XNS.
.PP
The following messages indicate a probable hardware error performing
the indicated operation during autoconfiguration or initialization.
The two control and status registers
should indicate the nature of the failure.
See the hardware manual for details.
.PP
\fBde%d: reset failed, csr0=%b csr1=%b\fP.
.PP
\fBde%d: ppcb failed, csr0=%b csr1=%b\fP.
.PP
\fBde%d: read addr failed, csr0=%b csr1=%b\fP.
.PP
\fBde%d: wtring failed, csr0=%b csr1=%b\fP.
.PP
\fBde%d: wtmode failed, csr0=%b csr1=%b\fP.
.SH SEE ALSO
netintro(4), inet(4), arp(4)
