.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)timedc.8	6.5 (Berkeley) 06/24/90
.\"
.TH TIMEDC 8 ""
.UC 6
.ad
.SH NAME
timedc \- timed control program
.SH SYNOPSIS
.B timedc
[ command [ argument ... ] ]
.SH DESCRIPTION
.I Timedc
is used to control the operation of the \fItimed\fP program.
It may be used to:
.IP \(bu
measure the differences between machines' clocks,
.IP \(bu
find the location where the master time server is running,
.IP \(bu
enable or disable tracing of messages received by \fItimed\fP, and
.IP \(bu
perform various debugging actions.
.PP
Without any arguments,
.I timedc
will prompt for commands from the standard input.
If arguments are supplied,
.IR timedc
interprets the first argument as a command and the remaining
arguments as parameters to the command.  The standard input
may be redirected causing
.I timedc
to read commands from a file.
Commands may be abbreviated;
recognized commands are:
.TP
? [ command ... ]
.TP
help [ command ... ]
.br
Print a short description of each command specified in the argument list,
or, if no arguments are given, a list of the recognized commands.
.TP
clockdiff host ...
.br
Compute the differences between the clock of the host machine
and the clocks of the machines given as arguments.
.TP
trace { on | off }
.br
Enable or disable the tracing of incoming messages to \fItimed\fP
in the file /var/log/timed.log.
.TP
quit
.br
Exit from timedc.
.PP
Other commands may be included for use in testing and debugging
.IR timed ;
the help command and
the program source may be consulted for details.
.SH FILES
.nf
.ta \w'/var/log/masterlog       'u
/var/log/timed.log		tracing file for timed
/var/log/timed.masterlog	log file for master timed
.fi
.SH "SEE ALSO"
date(1), adjtime(2), icmp(4), timed(8), 
.br
\fITSP: The Time Synchronization Protocol for UNIX 4.3BSD\fP, 
R. Gusella and S. Zatti
.SH DIAGNOSTICS
.nf
.ta \w'?Ambiguous command      'u
?Ambiguous command	abbreviation matches more than one command
?Invalid command	no match found
?Privileged command	command can be executed by root only
.fi
