.\" Copyright (c) 1983 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)lpc.8	6.3 (Berkeley) 06/24/90
.\"
.TH LPC 8 ""
.UC 5
.ad
.SH NAME
lpc \- line printer control program
.SH SYNOPSIS
.B lpc
[ command [ argument ... ] ]
.SH DESCRIPTION
.I Lpc
is used by the system administrator to control the
operation of the line printer system.  
For each line printer configured in /etc/printcap,
.I lpc
may be used to:
.IP \(bu
disable or enable a printer,
.IP \(bu
disable or enable a printer's spooling queue,
.IP \(bu
rearrange the order of jobs in a spooling queue,
.IP \(bu
find the status of printers, and their associated
spooling queues and printer dameons.
.PP
Without any arguments,
.I lpc
will prompt for commands from the standard input.
If arguments are supplied,
.IR lpc
interprets the first argument as a command and the remaining
arguments as parameters to the command.  The standard input
may be redirected causing
.I lpc
to read commands from file.
Commands may be abreviated;
the following is the list of recognized commands.
.TP
? [ command ... ]
.TP
help [ command ... ]
.br
Print a short description of each command specified in the argument list,
or, if no arguments are given, a list of the recognized commands.
.TP
abort { all | printer ... }
.br
Terminate an active spooling daemon on the local host immediately and
then disable printing (preventing new daemons from being started by
.IR lpr )
for the specified printers.
.TP
clean { all | printer ... }
.br
Remove any temporary files, data files, and control files that cannot
be printed (i.e., do not form a complete printer job)
from the specified printer queue(s) on the local machine.
.TP
disable { all | printer ... }
.br
Turn the specified printer queues off.  This prevents new
printer jobs from being entered into the queue by
.IR lpr .
.TP
down { all | printer } message ...
.br
Turn the specified printer queue off, disable printing and put
.I message
in the printer status file. The message doesn't need to be quoted, the
remaining arguments are treated like
.IR echo (1).
This is normally used to take a printer down and let others know why
(lpq will indicate the printer is down and print the status message).
.TP
enable { all | printer ... }
.br
Enable spooling on the local queue for the listed printers. 
This will allow
.I lpr
to put new jobs in the spool queue.
.TP
exit
.TP
quit
.br
Exit from lpc.
.TP
restart { all | printer ... }
.br
Attempt to start a new printer daemon. 
This is useful when some abnormal condition causes the daemon to
die unexpectedly leaving jobs in the queue.
.I Lpq
will report that there is no daemon present when this condition occurs. 
If the user is the super-user,
try to abort the current daemon first (i.e., kill and restart a stuck daemon).
.TP
start { all | printer ... }
.br
Enable printing and start a spooling daemon for the listed printers.
.TP
status { all | printer ... }
Display the status of daemons and queues on the local machine.
.TP
stop { all | printer ... }
.br
Stop a spooling daemon after the current job completes and disable
printing.
.TP
topq printer [ jobnum ... ] [ user ... ]
.br
Place the jobs in the order listed at the top of the printer queue.
.TP
up { all | printer ... }
.br
Enable everything and start a new printer daemon. Undoes the effects of
.IR down .
.SH FILES
.nf
.ta \w'/etc/printcap           'u
/etc/printcap	printer description file
/var/spool/*	spool directories
/var/spool/*/lock	lock file for queue control
.fi
.SH "SEE ALSO"
lpd(8),
lpr(1),
lpq(1),
lprm(1),
printcap(5)
.SH DIAGNOSTICS
.nf
.ta \w'?Ambiguous command      'u
?Ambiguous command	abreviation matches more than one command
?Invalid command	no match was found
?Privileged command	command can be executed by root only
.fi
