.\" Copyright (c) 1990 Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)ranlib.1	6.4 (Berkeley) 07/24/90
.\"
.Dd 
.Dt RANLIB 1
.BSD 4.4
.Sh NAME
.Nm ranlib
.Nd preprocess archives for efficient linking
.Sh SYNOPSIS
.Nm ranlib
.Op Fl t
.Ar archive_file ...
.Sh DESCRIPTION
.Nm Ranlib
is a preprocessor for the loading utility
.Xr ld 1 .
.Nm Ranlib
creates a randomized library from the given
.Ar archive_file
with
the file entry named
.Sy \&__.SYMDEF
prepended.
The
.Sy \&__.SYMDEF
file entry is a dictionary the loader can detect and interpret
to resolve external references at link time.
To generate the library, the
.Xr ar 1
utility is used.
.Tw 8n
.Tp Fl t
Ranlib only "touches" the archives and does not modify them.
This is useful after copying an archive
or using the
.Fl t
option of
.Xr make  1
in order to avoid having
.Xr ld  1
complain about
an
.Dq out of date
symbol table.
.Tp
.Sh SEE ALSO
.Xr ar 1 ,
.Xr ld 1 ,
.Xr lorder 1 ,
.Xr make 1 ,
.Xr nm 1
.Sh HISTORY
.Nm Ranlib
appeared in Version 7 AT&T UNIX.
.Sh BUGS
The archiving is a separate process and phase
errors may occur (see the
.Fl t
option above).
