#	@(#)Makefile	5.7 (Berkeley) 01/15/91

LIB=	util
CFLAGS+=-DLIBC_SCCS
SRCS=	daemon.c getloadavg.c login.c login_tty.c logout.c logwtmp.c kvm.c \
	pty.c pwcache.c
MAN3=	getloadavg.0 pwcache.0

.include <bsd.lib.mk>
