.\" Copyright (c) 1990 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" This code is derived from software contributed to Berkeley by
.\" Chris Torek.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)strcpy.3	5.2 (Berkeley) 06/24/90
.\"
.TH STRCPY 3 ""
.UC 4
.SH NAME
strcpy \- copy strings
.SH SYNOPSIS
.nf
.ft B
#include <string.h>

char *
strcpy(char *dst, const char *src);

char *
strncpy(char *dst, const char *src, size_t len);
.ft R
.fi
.SH DESCRIPTION
.B Strcpy
and
.B strncpy
copy string
.I src
to
.IR dst ,
stopping after the terminating '\e0' has been moved.
.PP
.B Strncpy
writes exactly
.I len
characters into
.IR dst ,
appending '\e0' characters if
.I src
is less than
.I len
characters long, and
.I not
terminating
.I dst
if
.I src
is more than
.I len
characters long.
.PP
.B Strcpy
and
.B strncpy
return
.IR dst .
.SH EXAMPLES
The following sets ``chararray'' to ``abc\e0\e0\e0'':
.sp
.ti +0.5i
(void)strncpy(chararray, "abc", 6).
.PP
The following sets ``chararray'' to ``abcdef'':
.sp
.RS
(void)strncpy(chararray, "abcdefgh", 6);
.RE
.SH SEE ALSO
bcopy(3), memccpy(3), memcpy(3), memmove(3)
.SH STANDARDS
.B Strcpy
and
.B strncpy
conform to ANSI X3.159-1989 (``ANSI C'').
