.\" Copyright (c) 1980 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)whereis.1	6.4 (Berkeley) 04/18/91
.\"
.TH WHEREIS 1 ""
.UC
.SH NAME
whereis \- locate source, binary, and or manual for program
.SH SYNOPSIS
.B whereis
[
.B \-sbm
] [
.B \-u
] [
.B \-SBM
dir ...
.B \-f
] name ...
.SH DESCRIPTION
.I Whereis
locates source/binary and manuals sections for specified files.
The supplied names are first stripped of leading pathname components
and any (single) trailing extension of the form ``.ext'', e.g. ``.c''.
Prefixes of ``s.'' resulting from use of source code control are also
dealt with.
.I Whereis
then attempts to locate the desired program in a list of standard places.
If any of the
.B \-b,
.B \-s
or
.B \-m
flags are given then
.I whereis
searches only for binaries, sources or manual sections respectively
(or any two thereof).
The
.B \-u
flag may be used to search for unusual entries.
A file is said to be unusual if it does not have one entry of
each requested type.
Thus ``whereis -m -u *'' asks for those files in the current
directory which have no documentation.
.sp
Finally, the
.B \-B
.B \-M
and
.B \-S
flags may be used to change or otherwise limit the places where
.I whereis
searches.
The
.B \-f
file flags is used to terminate the last such directory list
and signal the start of file names.
.SH EXAMPLE
The following finds all the files in /usr/bin which are not documented
in /usr/man/man1 with source in /usr/src/cmd:
.IP
cd /usr/ucb
.br
whereis \-u \-M /usr/man/man1 \-S /usr/src/cmd \-f *
.SH FILES
/usr/src/*
.br
/usr/{doc,man}/*
.br
/lib, /etc, /usr/{lib,bin,ucb,old,new,local}
.SH BUGS
Since the program uses
.IR chdir (2)
to run faster, pathnames given with the
.B \-M
.B \-S
and
.B \-B
must be full; i.e. they must begin with a ``/''.
