.\" Copyright (c) 1985 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)whois.1	6.4 (Berkeley) 12/13/90
.\"
.TH WHOIS 1 ""
.UC 6
.SH NAME
whois \- DARPA Internet user name directory service
.SH SYNOPSIS
.B whois
name
.SH DESCRIPTION
.TP
whois help
Produces a helpful message similar to the following:
.PP
Please enter a name or a handle (``ident"), such as ``Smith"
or ``SRI-NIC".
Starting with a period forces a name-only search;
starting with exclamation point forces handle-only.
Examples:
.nf
	Smith			[looks for name or handle SMITH	]
	!SRI-NIC			[looks for handle SRI-NIC only	]
	.Smith, John		[looks for name JOHN SMITH only	]
.fi
Adding ``..." to the argument will match anything from that point,
e.g. ``ZU..." will match ZUL, ZUM, etc.
.PP
To have the ENTIRE membership list of a group or organization,
if you are asking about a group or org, shown with the record, use
an asterisk character `*' directly preceding the given argument.
[CAUTION: If there are a lot of members this will take a long time!]
You may of course use exclamation point and asterisk, or a period
and asterisk together.
.SH SEE ALSO
RFC 812:  Nicname/Whois
