#	@(#)Makefile	5.8 (Berkeley) 07/20/92

SUBDIR=	bugfiler comsat fingerd ftpd getNAME getty mail.local \
	makekey rexecd rlogind rshd talkd telnetd tftpd uucpd

#KERBEROS=kpasswdd 

.include <bsd.subdir.mk>
