#	@(#)Makefile	8.1 (Berkeley) 06/06/93

PROG=	rlogin
SRCS=	rlogin.c
#SRCS=	rlogin.c krcmd.c kcmd.c des_rw.c
#DPADD=	${LIBKRB} ${LIBDES}
#CFLAGS+=-DKERBEROS
#LDADD=	-lkrb -ldes
BINOWN=	root
BINMODE=4555

.include <bsd.prog.mk>
