#!/bin/sh
#
# $Id: os-type,v 5.2 90/06/23 22:21:23 jsp Rel $
#
# Copyright (c) 1989 Jan-Simon Pendry
# Copyright (c) 1989 Imperial College of Science, Technology & Medicine
# Copyright (c) 1989 The Regents of the University of California.
# All rights reserved.
#
# This code is derived from software contributed to Berkeley by
# Jan-Simon Pendry at Imperial College, London.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. All advertising materials mentioning features or use of this software
#    must display the following acknowledgement:
#	This product includes software developed by the University of
#	California, Berkeley and its contributors.
# 4. Neither the name of the University nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#	@(#)os-type	5.1 (Berkeley) 06/29/90
#

#
# Take a pot-shot at your os type
#
echo "	... No OS= option specified; dynamically determining OS type" >&2

#
# First try poking around in /etc/motd
#

case "`exec 2>/dev/null; head -2 /etc/motd`" in
*"Sun UNIX 4.2 Release 3."*)	OS=sos3;;
*"SunOS Release 4."*)		OS=sos4;;
*"HP-UX on the HP"*)		OS=hpux;;
*"Ultrix V2."*)			OS=u2_2;;
*"Ultrix-32 V3."*)		OS=u3_0;;
*"Ultrix Worksystem V2.0"*)	OS=u3_0;;
*"HLH OTS Version 1."*)		OS=hlh42;;
*"RISC iX release 1."*)		OS=riscix;;
*"FPX 4."*)			OS=fpx4;;
*"4.4 BSD UNIX"*)		OS=bsd44;;
*"4.3 BSD UNIX"*)		if [ -f /etc/minidisk ]; then
					OS=acis43
				elif [ -f /sbin/nfsiod ]; then
					OS=bsd44	# prototype
				else
					OS=xinu43
				fi;;
*"Alliant Concentrix"*)		OS=concentrix;;
*"Umax 4.3"*)			OS=umax43;;
*)
#
# Well, that didn't work so apply some heuristics
# to the filesystem name space...
#
				echo "	... inspecting File system ..." >&2
				if [ -f /usr/bin/cat ]; then
					OS=sos4
				elif [ -f /etc/nd ]; then
					OS=sos3
				elif [ -f /etc/elcsd ]; then
					echo "	... Ultrix - assuming U3.0 ..." >&2
					OS=u3_0
				elif [ -f /hp-ux ]; then
					OS=hpux
				elif [ -f /etc/ttylocal ]; then
					OS=xinu43
				elif [ -f /etc/minidisk ]; then
					OS=acis43
				elif [ -f /etc/toolboxdaemon ]; then
					OS=aux
				elif [ -f /sbin/nfsiod ]; then
					OS=bsd44
				elif [ -d /vrm ]; then
					OS=aix2
				elif [ -d /etc/aix ]; then
					OS=aix3
				elif [ -f /bin/pyr ] && /bin/pyr; then
					OS=pyrOSx
				else
					case "`(sh arch)2>/dev/null`" in
					powernode) OS=utx32;;
					ibm032)    OS=acis43;;
					*)	   OS=unknown;;
					esac
				fi;;
esac

echo "	... OS appears to be \"${OS}\"" >&2
echo "${OS}"
exit 0
